name: Check

on:
  push:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install
        run: npm install

      - name: Lint
        run: npm run lint

      - name: Typecheck
        run: npm run lint:ts

      - name: Format
        run: npm run format:check

      - name: Build
        run: npm run build

      - name: Test
        run: npm run test:ci

      - name: Upload coverage
        uses: codecov/codecov-action@v3
