name:

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v3
      - name: Starting Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Lint
        run: npm run lint

      - name: Typecheck
        run: npm run lint:ts

      - name: Format
        run: npm run format:check

      - name: Build
        run: npm run build

      - name: Test unit
        run: npm run test:unit

      - name: Test CI
        run: npm run test:ci

      - name: Upload coverage
        uses: codecov/codecov-action@v3
